package com.change_vision.astah.extension.plugin.easycodereverse.internal.util;

import org.apache.commons.lang.ArrayUtils;

public class JavaTypeUtil {
	public static final String JAVA_LANG_PACKAGE = "java.lang";
	
	public static boolean isVoid(String type) {
		return "void".equals(type);
	}
	
	public static boolean isPrimitive(String type) {
		return ArrayUtils.contains(new String[] { "boolean", "char",
				"byte", "short", "int", "long", "float", "double" },
				type);
	}
	
	public static boolean isJavaLang(String type) {
		return ArrayUtils.contains(new String[] {
				"AbstractMethodError",
				"Appendable",
				"ArithmeticException",
				"ArrayIndexOutOfBoundsException",
				"ArrayStoreException",
				"AssertionError",
				"AutoCloseable",
				"Boolean",
				"BootstrapMethodError",
				"Byte",
				"CharSequence",
				"Character.Subset",
				"Character.UnicodeBlock",
				"Character.UnicodeScript",
				"Character",
				"Class",
				"ClassCastException",
				"ClassCircularityError",
				"ClassFormatError",
				"ClassLoader",
				"ClassNotFoundException",
				"ClassValue",
				"CloneNotSupportedException",
				"Cloneable",
				"Comparable",
				"Compiler",
				"Deprecated",
				"Double",
				"Enum",
				"EnumConstantNotPresentException",
				"Error",
				"Exception",
				"ExceptionInInitializerError",
				"Float",
				"IllegalAccessError",
				"IllegalAccessException",
				"IllegalArgumentException",
				"IllegalMonitorStateException",
				"IllegalStateException",
				"IllegalThreadStateException",
				"IncompatibleClassChangeError",
				"IndexOutOfBoundsException",
				"InheritableThreadLocal",
				"InstantiationError",
				"InstantiationException",
				"Integer",
				"InternalError",
				"InterruptedException",
				"Iterable",
				"LinkageError",
				"Long",
				"Math",
				"NegativeArraySizeException",
				"NoClassDefFoundError",
				"NoSuchFieldError",
				"NoSuchFieldException",
				"NoSuchMethodError",
				"NoSuchMethodException",
				"NullPointerException",
				"Number",
				"NumberFormatException",
				"Object",
				"OutOfMemoryError",
				"Override",
				"Package",
				"Process",
				"ProcessBuilder.Redirect.Type",
				"ProcessBuilder.Redirect",
				"ProcessBuilder",
				"Readable",
				"ReflectiveOperationException",
				"Runnable",
				"Runtime",
				"RuntimeException",
				"RuntimePermission",
				"SafeVarargs",
				"SecurityException",
				"SecurityManager",
				"Short",
				"StackOverflowError",
				"StackTraceElement",
				"StrictMath",
				"String",
				"StringBuffer",
				"StringBuilder",
				"StringIndexOutOfBoundsException",
				"SuppressWarnings",
				"System",
				"Thread.State",
				"Thread.UncaughtExceptionHandler",
				"Thread",
				"ThreadDeath",
				"ThreadGroup",
				"ThreadLocal",
				"Throwable",
				"TypeNotPresentException",
				"UnknownError",
				"UnsatisfiedLinkError",
				"UnsupportedClassVersionError",
				"UnsupportedOperationException",
				"VerifyError",
				"VirtualMachineError",
				"Void"
		}, type);
	}
}
